import assert from "node:assert/strict";import{mkdtempSync,rmSync}from"node:fs";import{tmpdir}from"node:os";import{join}from"node:path";import type{DiceRoller}from"../packages/rules-core/src/index.js";import{Dnd5eRuleset,create5eActor}from"../packages/rules-dnd5e/src/index.js";import{CampaignEngine,FactLedger}from"../packages/campaign-engine/src/index.js";import{SaveStore}from"../packages/persistence/src/index.js";
class Fixed implements DiceRoller{constructor(private r:number[]){}d20(){const x=this.r.shift();if(x===undefined)throw Error("no roll");return x}roll(_s:number,count=1){return Array.from({length:count},()=>{const x=this.r.shift();if(x===undefined)throw Error("no roll");return x})}}
const sword={id:"longsword",name:"Longsword",ability:"str" as const,damageDice:{count:1,sides:8},damageType:"slashing",proficient:true};
const pc=create5eActor({id:"pc1",name:"Aria",controllerId:"c1",abilities:{str:16,dex:14,wis:12},armorClass:16,hp:12,skills:["perception"],saves:["str"],weapons:[sword]});
const gob=create5eActor({id:"g1",name:"Goblin",kind:"creature",controllerId:"dm",abilities:{dex:14},armorClass:12,hp:7,weapons:[]});
const campaign={id:"test",title:"Test",rulesetId:"dnd-5e-2024",rulesVersion:"srd-5.2.1",startSceneId:"room",scenes:[{id:"room",name:"Room",description:"",exits:[]}],canon:[]};
const engine=new CampaignEngine(campaign,new Dnd5eRuleset());const state=engine.createGame({participants:[{id:"p1",name:"Alice",kind:"human",controllerId:"c1",actorIds:["pc1"]}],controllers:[{id:"c1",kind:"human",participantId:"p1"},{id:"dm",kind:"ai-dm"}],actors:[pc,gob]});
assert.equal((state as any).player,undefined);assert.equal(state.participants.length,1);assert.equal(state.actors.length,2);
const check=engine.check(state,"pc1",{ability:"wis",skill:"perception",dc:15,reason:"Spot clue"},new Fixed([12]));assert.equal(check.modifier,3);assert.equal(check.total,15);assert.equal(check.success,true);
const adv=engine.check(state,"pc1",{ability:"str",dc:18,reason:"Lift",advantage:"advantage"},new Fixed([4,17]));assert.equal(adv.die,17);assert.equal(adv.success,true);
engine.startEncounter(state,"e1",["pc1","g1"],new Fixed([10,8]));assert.equal(state.encounter?.initiative[0]?.actorId,"pc1");
const hit=engine.attack(state,"pc1","g1","longsword",new Fixed([15,5]));assert.equal(hit.success,true);assert.equal(hit.damage,8);assert.equal(hit.targetDefeated,true);
const dir=mkdtempSync(join(tmpdir(),"airpg06-"));try{const store=new SaveStore(join(dir,"x.sqlite"));store.upsert(state);const loaded=store.load(state.id)!;assert.equal(loaded.rulesVersion,"srd-5.2.1");assert.equal(loaded.actors.length,2);store.close()}finally{rmSync(dir,{recursive:true,force:true})}
const ledger=new FactLedger();ledger.add({id:"f1",subject:"Harbormaster",predicate:"uses",value:"blue wax",source:"authored_canon",visibility:["player"],protection:"established",confidence:"explicit",provenance:"test"});ledger.add({id:"f2",subject:"Letter",predicate:"sender",value:"unknown secret",source:"authored_canon",visibility:["dm_only"],protection:"protected",confidence:"explicit",provenance:"test"});assert.equal(ledger.relevant({viewer:"pc1",terms:["blue wax"]})[0]?.id,"f1");assert.equal(ledger.relevant({viewer:"pc1",terms:["secret"]}).length,0);assert.equal(ledger.relevant({viewer:"pc1",terms:["completely unrelated"]}).length,0);
console.log("V0.6 golden foundation tests PASS");
