import type {Actor,CampaignDefinition,Controller,GameEvent,GameState,Participant} from "../../domain/src/index.js"; import {actorById} from "../../domain/src/index.js"; import type {DiceRoller,Ruleset} from "../../rules-core/src/index.js";
const ev=(type:GameEvent["type"],payload:unknown):GameEvent=>({id:crypto.randomUUID(),type,at:new Date().toISOString(),payload});
export class CampaignEngine{constructor(readonly campaign:CampaignDefinition,readonly ruleset:Ruleset){if(campaign.rulesetId!==ruleset.id||campaign.rulesVersion!==ruleset.version)throw new Error("Campaign/ruleset version mismatch")}
 createGame(input:{participants:Participant[];controllers:Controller[];actors:Actor[];difficulty?:GameState["difficulty"]}):GameState{for(const a of input.actors){const errors=this.ruleset.validateActor(a);if(errors.length)throw new Error(`${a.name}: ${errors.join(", ")}`)}return{schemaVersion:1,id:crypto.randomUUID(),campaignId:this.campaign.id,rulesetId:this.ruleset.id,rulesVersion:this.ruleset.version,currentSceneId:this.campaign.startSceneId,difficulty:input.difficulty??"normal",participants:input.participants,controllers:input.controllers,actors:input.actors,facts:[...this.campaign.canon],ledger:[],knowledge:[],flags:{},events:[ev("GAME_STARTED",{campaignId:this.campaign.id,participantIds:input.participants.map(x=>x.id)})]}}
 enterScene(state:GameState,sceneId:string){if(!this.campaign.scenes.some(scene=>scene.id===sceneId))throw new Error(`Unknown scene '${sceneId}'`);state.currentSceneId=sceneId;state.events.push(ev("SCENE_ENTERED",{sceneId}))}
 giveItem(state:GameState,actorId:string,itemId:string){const actor=actorById(state,actorId);const existing=actor.inventory.find(item=>item.itemId===itemId);if(existing)existing.quantity+=1;else actor.inventory.push({itemId,quantity:1});state.events.push(ev("ITEM_GAINED",{actorId,itemId}))}
 applyDamage(state:GameState,actorId:string,amount:number){const actor=actorById(state,actorId);const hp=(actor.rulesData as {hitPoints?:{current:number}}).hitPoints;if(!hp)throw new Error(`${actor.name} has no hit points`);const dealt=Math.max(0,amount);hp.current=Math.max(0,hp.current-dealt);state.events.push(ev("DAMAGE_APPLIED",{targetId:actorId,amount:dealt,type:"bludgeoning"}));if(hp.current===0)state.events.push(ev("ACTOR_DEFEATED",{actorId}));return hp.current}
 endEncounter(state:GameState){const encounter=state.encounter;if(!encounter?.active)return;encounter.active=false;state.events.push(ev("ENCOUNTER_ENDED",{id:encounter.id}))}
 check(state:GameState,actorId:string,request:{ability:string;skill?:string;dc:number;reason:string;advantage?:"normal"|"advantage"|"disadvantage"},dice?:DiceRoller){state.events.push(ev("CHECK_REQUESTED",{actorId,...request}));const result=this.ruleset.resolveCheck(actorById(state,actorId),request,dice);state.events.push(ev("CHECK_RESOLVED",{actorId,...request,...result}));return result}
 save(state:GameState,actorId:string,request:{ability:string;dc:number;reason:string;advantage?:"normal"|"advantage"|"disadvantage"},dice?:DiceRoller){state.events.push(ev("SAVE_REQUESTED",{actorId,...request}));const result=this.ruleset.resolveSavingThrow(actorById(state,actorId),request,dice);state.events.push(ev("SAVE_RESOLVED",{actorId,...request,...result}));return result}
 startEncounter(state:GameState,id:string,actorIds:string[],dice?:DiceRoller){const initiative=actorIds.map(x=>this.ruleset.rollInitiative(actorById(state,x),dice)).sort((a,b)=>b.total-a.total||a.actorId.localeCompare(b.actorId));state.encounter={id,active:true,round:1,turnIndex:0,initiative,actorIds};state.events.push(ev("ENCOUNTER_STARTED",{id,initiative}));state.events.push(ev("TURN_STARTED",{actorId:initiative[0]?.actorId,round:1}));return initiative}
 attack(state:GameState,attackerId:string,targetId:string,actionId:string,dice?:DiceRoller){const result=this.ruleset.resolveAttack(actorById(state,attackerId),actorById(state,targetId),actionId,dice);state.events.push(ev("ATTACK_RESOLVED",{attackerId,targetId,actionId,...result}));if(result.damage)state.events.push(ev("DAMAGE_APPLIED",{targetId,amount:result.damage,type:result.damageType}));if(result.targetDefeated)state.events.push(ev("ACTOR_DEFEATED",{actorId:targetId}));return result}
 endTurn(state:GameState){const e=state.encounter;if(!e?.active)throw new Error("No active encounter");state.events.push(ev("TURN_ENDED",{actorId:e.initiative[e.turnIndex]?.actorId,round:e.round}));e.turnIndex++;if(e.turnIndex>=e.initiative.length){e.turnIndex=0;e.round++}state.events.push(ev("TURN_STARTED",{actorId:e.initiative[e.turnIndex]?.actorId,round:e.round}))}
}
export * from "./fact-ledger.js";

export * from "./narrative-authority.js";
