import type { Actor } from "../../domain/src/index.js";
import { RandomDiceRoller,d20WithState,type AttackResolution,type DiceRoller,type RollResult,type Ruleset } from "../../rules-core/src/index.js";
export type Ability="str"|"dex"|"con"|"int"|"wis"|"cha";
export interface Dnd5eWeapon { id:string; name:string; ability:Ability; damageDice:{count:number;sides:number}; damageType:string; proficient:boolean; }
export interface Dnd5eData { level:number; proficiencyBonus:number; abilities:Record<Ability,number>; skillProficiencies:string[]; saveProficiencies:Ability[]; armorClass:number; hitPoints:{current:number;maximum:number;temporary:number}; speed:number; weapons:Dnd5eWeapon[]; deathSaves:{successes:number;failures:number;stable:boolean}; }
const SKILL_ABILITY:Record<string,Ability>={acrobatics:"dex",animalHandling:"wis",arcana:"int",athletics:"str",deception:"cha",history:"int",insight:"wis",intimidation:"cha",investigation:"int",medicine:"wis",nature:"int",perception:"wis",performance:"cha",persuasion:"cha",religion:"int",sleightOfHand:"dex",stealth:"dex",survival:"wis"};
export const abilityModifier=(score:number)=>Math.floor((score-10)/2);
function data(actor:Actor):Dnd5eData { if(actor.rulesetId!=="dnd-5e-2024")throw new Error(`${actor.name} is not a dnd-5e-2024 actor`); return actor.rulesData as Dnd5eData; }
export class Dnd5eRuleset implements Ruleset { readonly id="dnd-5e-2024"; readonly version="srd-5.2.1";
 validateActor(actor:Actor){const d=data(actor),e:string[]=[]; if(d.hitPoints.maximum<1)e.push("maximum HP must be positive"); for(const a of Object.values(d.abilities))if(a<1||a>30)e.push("ability scores must be 1..30"); return e}
 resolveCheck(actor:Actor,r:{ability:string;skill?:string;dc:number;advantage?:"normal"|"advantage"|"disadvantage"},dice:DiceRoller=new RandomDiceRoller()):RollResult { const d=data(actor), ability=(r.skill?SKILL_ABILITY[r.skill]:r.ability) as Ability; if(!ability||d.abilities[ability]===undefined)throw new Error(`Unknown ability/skill`); const mod=abilityModifier(d.abilities[ability])+(r.skill&&d.skillProficiencies.includes(r.skill)?d.proficiencyBonus:0); const state=r.advantage??"normal",die=d20WithState(dice,state),total=die+mod; return {die,modifier:mod,total,target:r.dc,success:total>=r.dc,advantageState:state}; }
 resolveSavingThrow(actor:Actor,r:{ability:string;dc:number;advantage?:"normal"|"advantage"|"disadvantage"},dice:DiceRoller=new RandomDiceRoller()):RollResult { const d=data(actor),a=r.ability as Ability; const mod=abilityModifier(d.abilities[a])+(d.saveProficiencies.includes(a)?d.proficiencyBonus:0),state=r.advantage??"normal",die=d20WithState(dice,state),total=die+mod; return {die,modifier:mod,total,target:r.dc,success:total>=r.dc,advantageState:state}; }
 rollInitiative(actor:Actor,dice:DiceRoller=new RandomDiceRoller()){const d=data(actor),die=dice.d20(),modifier=abilityModifier(d.abilities.dex);return {actorId:actor.id,die,modifier,total:die+modifier}}
 resolveAttack(attacker:Actor,target:Actor,actionId:string,dice:DiceRoller=new RandomDiceRoller()):AttackResolution { const a=data(attacker),t=data(target),w=a.weapons.find(x=>x.id===actionId); if(!w)throw new Error(`Unknown weapon action '${actionId}'`); const die=dice.d20(),modifier=abilityModifier(a.abilities[w.ability])+(w.proficient?a.proficiencyBonus:0),total=die+modifier,critical=die===20,success=die!==1&&(critical||total>=t.armorClass); let damage=0;if(success){const rolls=dice.roll(w.damageDice.sides,w.damageDice.count*(critical?2:1));damage=Math.max(0,rolls.reduce((x,y)=>x+y,0)+abilityModifier(a.abilities[w.ability]));let remaining=damage;if(t.hitPoints.temporary>0){const used=Math.min(t.hitPoints.temporary,remaining);t.hitPoints.temporary-=used;remaining-=used}t.hitPoints.current=Math.max(0,t.hitPoints.current-remaining)} return {die,modifier,total,target:t.armorClass,success,critical,damage,damageType:w.damageType,targetHp:t.hitPoints.current,targetDefeated:t.hitPoints.current===0}; }
 rest(actor:Actor,kind:"short"|"long"){const d=data(actor);if(kind==="long"){d.hitPoints.current=d.hitPoints.maximum;d.deathSaves={successes:0,failures:0,stable:false};for(const r of actor.resources)if(!r.resetsOn||r.resetsOn==="long-rest")r.current=r.maximum}else for(const r of actor.resources)if(r.resetsOn==="short-rest")r.current=r.maximum}
}
export function create5eActor(input:{id:string;name:string;kind?:Actor["kind"];controllerId?:string;level?:number;abilities?:Partial<Record<Ability,number>>;armorClass?:number;hp?:number;skills?:string[];saves?:Ability[];weapons?:Dnd5eWeapon[]}):Actor<Dnd5eData>{const base:Record<Ability,number>={str:10,dex:10,con:10,int:10,wis:10,cha:10};const level=input.level??1;return {id:input.id,name:input.name,kind:input.kind??"player-character",rulesetId:"dnd-5e-2024",controllerId:input.controllerId,inventory:[],resources:[],effects:[],rulesData:{level,proficiencyBonus:2,abilities:{...base,...input.abilities},skillProficiencies:input.skills??[],saveProficiencies:input.saves??[],armorClass:input.armorClass??10,hitPoints:{current:input.hp??10,maximum:input.hp??10,temporary:0},speed:30,weapons:input.weapons??[],deathSaves:{successes:0,failures:0,stable:false}}}}
